[package]
authors = ["The Rust Project Developers"]
description = "A collection of numeric types and traits for Rust, including bigint,\ncomplex, rational, range iterators, generic integers, and more!\n"
documentation = "https://docs.rs/num"
homepage = "https://github.com/rust-num/num"
keywords = ["mathematics", "numerics", "bignum"]
categories = [ "algorithms", "data-structures", "science" ]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-num/num"
name = "num"
version = "0.2.0-git"
publish = false
readme = "README.md"

[badges]
travis-ci = { repository = "rust-num/num" }

[dependencies]

[dependencies.num-bigint]
optional = true
version = "0.2.0"

[dependencies.num-complex]
optional = true
version = "0.2.0"

[dependencies.num-integer]
version = "0.1.36"

[dependencies.num-iter]
version = "0.1.35"

[dependencies.num-rational]
optional = true
version = "0.2.0"

[dependencies.num-traits]
version = "0.2.0"

[dev-dependencies]

[features]
bigint = ["num-bigint"]
complex = ["num-complex"]
rational = ["num-rational"]
default = ["bigint", "num-bigint/rand", "complex", "rational"]

rand = [
  "num-bigint/rand",
  "num-complex/rand",
]
serde = [
  "num-bigint/serde",
  "num-complex/serde",
  "num-rational/serde"
]
